/**
 * LeadsheetExporter.js - Export progressions to Impro-Visor .ls format
 *
 * Generates leadsheet files compatible with:
 * - Impro-Visor (Java app for jazz improvisation)
 * - lstmprovisor-python (LSTM training)
 * - iReal Pro (with minor adjustments)
 */

import { JAZZ_DEGREES } from '../engine/JazzDegrees.js'

/**
 * Map RameauJazz chord types to Impro-Visor notation
 */
const CHORD_TYPE_MAP = {
  'maj7': 'M7',
  'maj9': 'M9',
  'maj6': 'M6',
  '7': '7',
  '9': '9',
  '13': '13',
  'm7': 'm7',
  'm9': 'm9',
  'm6': 'm6',
  'mMaj7': 'mM7',
  'm7b5': 'm7b5',
  'dim7': 'o7',
  'aug7': '7#5',
  '7b9': '7b9',
  '7#9': '7#9',
  '7b13': '7b13',
  '7alt': '7alt',
  '7sus': '7sus4',
  '7#11': '7#11',
  '13b9': '13b9',
  '7#5#9': '7#5#9',
  '7b5': '7b5'
}

/**
 * Map key names to Impro-Visor root notation
 */
const ROOT_MAP = {
  'C': 'C', 'Db': 'Db', 'D': 'D', 'Eb': 'Eb', 'E': 'E', 'F': 'F',
  'Gb': 'Gb', 'G': 'G', 'Ab': 'Ab', 'A': 'A', 'Bb': 'Bb', 'B': 'B'
}

/**
 * Note names for calculating chord roots
 */
const NOTE_NAMES = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B']

/**
 * Key signature mapping (number of flats/sharps)
 * Negative = flats, Positive = sharps
 */
const KEY_SIGNATURES = {
  'C': 0, 'G': 1, 'D': 2, 'A': 3, 'E': 4, 'B': 5,
  'F': -1, 'Bb': -2, 'Eb': -3, 'Ab': -4, 'Db': -5, 'Gb': -6
}

/**
 * Convert a RameauJazz degree to Impro-Visor chord symbol
 */
function degreeToChordSymbol(degree, key) {
  const degreeInfo = JAZZ_DEGREES[degree]
  if (!degreeInfo) return 'NC'

  // Calculate absolute root
  const keyIndex = NOTE_NAMES.indexOf(key)
  const rootIndex = (keyIndex + degreeInfo.root + 12) % 12
  const rootName = NOTE_NAMES[rootIndex]

  // Map chord type
  const chordType = CHORD_TYPE_MAP[degreeInfo.type] || 'M7'

  return rootName + chordType
}

/**
 * Generate Impro-Visor leadsheet content
 */
export function generateLeadsheet(options) {
  const {
    progression,
    key = 'C',
    tempo = 120,
    title = 'RameauJazz Progression',
    composer = 'Generated',
    style = 'swing'
  } = options

  // Header
  const keySig = KEY_SIGNATURES[key] || 0
  const styleMap = {
    'standard': 'swing',
    'bebop': 'swing-fast',
    'bossaNova': 'bossa-nova',
    'modal': 'swing',
    'ballad': 'ballad'
  }
  const ivStyle = styleMap[style] || 'swing'

  let ls = `(title ${title})
(composer ${composer})
(show )
(year ${new Date().getFullYear()})
(comments Generated by RameauJazz Web)
(meter 4 4)
(key ${keySig})
(tempo ${tempo}.0)
(volume 80)
(playback-transpose 0)
(chord-font-size 16)
(bass-instrument 33)
(bass-volume 80)
(drum-volume 60)
(chord-volume 80)
(breakpoint 54)
(layout 4)
(roadmap-layout 8)
(style ${ivStyle}
    (swing 0.67)
    (comp-swing 0.67)
    (bass-high g-)
    (bass-low g---)
    (chord-high a)
    (chord-low c-)
    (chord-base c- e- g-)
)
(part
    (type chords)
    (title )
    (composer )
    (instrument 0)
    (volume 80)
    (key ${keySig})
)

(section (style ${ivStyle}))

`

  // Generate chord bars
  const bars = []
  let currentKey = key

  for (const chord of progression) {
    // Update key if modulated
    if (chord.key && chord.key !== currentKey) {
      currentKey = chord.key
    }

    const symbol = degreeToChordSymbol(chord.degree, currentKey)
    bars.push(symbol)
  }

  // Format as 4 bars per line
  for (let i = 0; i < bars.length; i += 4) {
    const line = bars.slice(i, i + 4)
    ls += line.join(' | ') + ' | \n'
  }

  // Add empty melody part (required by format)
  ls += `
(part
    (type melody)
    (title )
    (composer )
    (instrument 0)
    (volume 85)
    (key ${keySig})
    (stave treble)
)
 r1`

  // Add rests for remaining measures
  for (let i = 1; i < progression.length; i++) {
    ls += '+1'
  }
  ls += '\n'

  return ls
}

/**
 * Export and download as .ls file
 */
export function exportLeadsheet(options) {
  const content = generateLeadsheet(options)
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)

  const link = document.createElement('a')
  link.href = url
  link.download = `${options.title || 'progression'}.ls`
  link.click()

  URL.revokeObjectURL(url)
}

/**
 * Generate iReal Pro format (simplified)
 * Format: Title=Comp=Style=Key=Chords
 */
export function generateiRealPro(options) {
  const { progression, key = 'C', title = 'RameauJazz', style = 'standard' } = options

  const styleMap = {
    'standard': 'Medium Swing',
    'bebop': 'Up Tempo Swing',
    'bossaNova': 'Bossa Nova',
    'modal': 'Medium Swing',
    'ballad': 'Ballad'
  }

  let currentKey = key
  const chords = progression.map(chord => {
    if (chord.key) currentKey = chord.key
    return degreeToChordSymbol(chord.degree, currentKey)
  })

  // iReal uses | for bar lines and spaces between chords
  const chordStr = chords.join(' ')

  return `irealbook://${encodeURIComponent(title)}==${encodeURIComponent('Generated')}=${styleMap[style] || 'Medium Swing'}=${key}=n=${chordStr}`
}

/**
 * Generate plain text chord chart
 */
export function generateChordChart(options) {
  const { progression, key = 'C', tempo = 120, title = 'Progression' } = options

  let chart = `${title}\n`
  chart += `Key: ${key} | Tempo: ${tempo} BPM\n`
  chart += '─'.repeat(40) + '\n\n'

  let currentKey = key
  const bars = []

  for (const chord of progression) {
    if (chord.key) currentKey = chord.key
    const symbol = degreeToChordSymbol(chord.degree, currentKey)
    const keyMarker = chord.key && chord.key !== key ? ` [${chord.key}]` : ''
    bars.push(symbol + keyMarker)
  }

  // Format as 4 bars per line
  for (let i = 0; i < bars.length; i += 4) {
    const line = bars.slice(i, i + 4)
    chart += '| ' + line.map(b => b.padEnd(10)).join('| ') + '|\n'
  }

  return chart
}

export default {
  generateLeadsheet,
  exportLeadsheet,
  generateiRealPro,
  generateChordChart
}
